### ISSUE TITLE
Missing compatibility with Pyglet 2.0

### ISSUE THREAD

**Issue by onitake** [jonathanwin/yagv#25]
We have a bug report on the Debian bug tracker that indicates yagv isn't compatible with Pyglet 2.0:
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1064598

The symptom is that yagv tries to use Pyglet's graphics primitives in a way that is no longer supported, and crashes:
```
generating graphics...
Traceback (most recent call last):
  File "/usr/bin/yagv", line 503, in <module>
    App().main()
  File "/usr/bin/yagv", line 39, in main
    self.load(path)
  File "/usr/bin/yagv", line 81, in load
    self.generateGraphics()
  File "/usr/bin/yagv", line 188, in generateGraphics
    vertex_list = pyglet.graphics.vertex_list(nb_layer_vertices,
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'pyglet.graphics' has no attribute 'vertex_list'
```

Please consider upgrading yagv to use the new graphics pipeline.
Migration instructions can be found here: https://pyglet.readthedocs.io/en/latest/programming_guide/migration.html

**Comment by EtherGraf** [comment]
See my pull request #26
