### ISSUE TITLE
G1 code parse error

### ISSUE THREAD

**Issue by chexov** [jonathanwin/yagv#7]
python yagv  ~/3dprint/Toy_Helicopter/helicopter_tail_rotor_plug.gcode 
Yet Another GCode Viewer v0.4
loading file '/Users/chexov/3dprint/Toy_Helicopter/helicopter_tail_rotor_plug.gcode' ...

Parsing '/Users/chexov/3dprint/Toy_Helicopter/helicopter_tail_rotor_plug.gcode'...

[WARN] Line 10: Unknown code 'M107' (Text:'M107')
Traceback (most recent call last):
  File "yagv", line 503, in <module>
    App().main()
  File "yagv", line 42, in main
    self.load(path)
  File "yagv", line 70, in load
    self.model = parser.parseFile(path)
  File "/Users/chexov/code/yagv/gcodeParser.py", line 22, in parseFile
    self.parseLine()
  File "/Users/chexov/code/yagv/gcodeParser.py", line 45, in parseLine
    getattr(self, "parse_"+code)(args)
  File "/Users/chexov/code/yagv/gcodeParser.py", line 62, in parse_G0
    self.G1(args, "G0")
AttributeError: GcodeParser instance has no attribute 'G1'

**Comment by petterreinholdtsen** [comment]
This issue is fixed by pull requests #4, #8 and #11.

**Comment by jonathanwin** [comment]
Fixed in master, thanks for reporting
